import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PriceMarquee from "@/components/PriceMarquee";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import AuthRedirectHandler from "@/components/AuthRedirectHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const banglaFont = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <Header />
        <PriceMarquee />
        <main>
          <Toaster position="top-center" toastOptions={{
            duration: 3000,
            style: {
              fontFamily: "'Hind Siliguri', sans-serif",
            },
          }} />
          <Suspense fallback={null}>
            <AuthRedirectHandler />
          </Suspense>

          {children}

        </main>
        <Footer />
      </body>
    </html>
  );
}
